//389. Find the Difference
/*
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.
*/
const frequencyMap = (str) =>
	[...str].reduce((h, c) => ((h[c] = h[c] + 1 || 1), h), {});

const findTheDifference = (s, t) => {
	const [m1, m2] = [s, t].map(frequencyMap);
	return [...t].find((char) => m1[char] !== m2[char]);
};
